//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astro_db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paneta
    {
        public int Id { get; set; }
        public string Nosaukums { get; set; }
        public Nullable<int> Vid_att_no_Saules { get; set; }
        public string Vid_Radiuss__atiec_pret_zemi { get; set; }
        public string Tilpums__attiec_pret_zemi { get; set; }
        public string Masa { get; set; }
        public Nullable<double> Blivums { get; set; }
        public Nullable<double> Gravitacija_uz__ekvatora { get; set; }
        public Nullable<double> Otrias_kos_atrums { get; set; }
        public Nullable<double> Rotacijas_periods { get; set; }
        public Nullable<double> Aprink_periods { get; set; }
        public Nullable<double> Vid_orbitalais_atrums { get; set; }
        public Nullable<int> Virsmas_vid_temp { get; set; }
        public Nullable<int> Vid_temp { get; set; }
        public string Atmosferas_sastavs { get; set; }
        public Nullable<int> Dab_pavadoni { get; set; }
        public string Gredzeni { get; set; }
        public string Apraksts { get; set; }
    }
}
